# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2], 
               [4, 5]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]],
              [[19, 20, 21],
               [22, 23, 24],
               [25, 26, 27]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.dtype, a1.size, type(a1)

((3,), dtype('int64'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.dtype, a2.size, type(a2)

((2, 2), dtype('int64'), 4, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.dtype, a3.size, type(a3)

((3, 3, 3), dtype('int64'), 27, numpy.ndarray)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
pda1 = pd.DataFrame(a1)
pda1

0
0  1
1  2
2  3

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
a4 = np.array(range(0, 100, 3))
a4

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ra1 = np.random.randint(0, 10, size=(7, 2))
ra1

array([[7, 9],
       [8, 5],
       [7, 9],
       [2, 6],
       [6, 1],
       [3, 5],
       [2, 2]], dtype=int32)

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ra2 = np.random.random((3, 5))
ra2

array([[0.2064091 , 0.36723803, 0.94905028, 0.23975736, 0.89295906],
       [0.0656244 , 0.57165964, 0.32492683, 0.64535394, 0.51696895],
       [0.48614338, 0.56382287, 0.82398504, 0.7364934 , 0.70926768]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
ra3 = np.random.randint(0, 10, size=(4, 6))
ra3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
ra4 = np.random.randint(1, 10, (3, 7))

# Find the unique numbers in the array you just created
np.unique(ra4)

array([1, 2, 3, 4, 5, 7, 9], dtype=int32)

In [14]:
ra4

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]], dtype=int32)

In [15]:
# Find the 0'th index of the latest array you created
ra4[2, 0]

np.int32(4)

In [16]:
# Get the first 2 rows of latest array you created
ra4[:2,]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]], dtype=int32)

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
ra4[:2, :2]

array([[9, 1],
       [5, 3]], dtype=int32)

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
ra5 = np.random.randint(0, 10, size=(3, 5))
ones = np.ones((3, 5))

In [19]:
# Add the two arrays together
ra5 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [20]:
# Create another array of ones of shape (5, 3)
ra6 = ra5.reshape(5, 3)


In [21]:
# Try add the array of ones and the other most recent array together
ra6 + ones

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [32]:
# Create another array of ones of shape (3, 5)
ra6 = ra6.reshape(3, 5)
ones = ones.reshape(3, 5)
ones, ra6

(array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5],
        [5, 9, 3, 5, 1]], dtype=int32))

In [33]:
# Subtract the new array of ones from the other most recent array
rez1 = ra6 - ones
rez1

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [34]:
# Multiply the ones array with the latest array
rez2 = rez1 * ones
rez2

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [37]:
# Take the latest array to the power of 2 using '**'
rez3 = rez2 ** 2
rez3

array([[25., 36.,  1.,  1.,  4.],
       [ 0., 36.,  4.,  0., 16.],
       [16., 64.,  4., 16.,  0.]])

In [38]:
# Do the same thing with np.square()
rez4 = np.square(rez2)
rez4

array([[25., 36.,  1.,  1.,  4.],
       [ 0., 36.,  4.,  0., 16.],
       [16., 64.,  4., 16.,  0.]])

In [39]:
# Find the mean of the latest array using np.mean()
np.mean(rez4)

np.float64(14.866666666666667)

In [40]:
# Find the maximum of the latest array using np.max()
np.max(rez4)

np.float64(64.0)

In [41]:
# Find the minimum of the latest array using np.min()
np.min(rez4)

np.float64(0.0)

In [42]:
# Find the standard deviation of the latest array
np.std(rez4)

np.float64(17.917837171067518)

In [43]:
# Find the variance of the latest array
np.var(rez4)

np.float64(321.0488888888889)

In [45]:
# Reshape the latest array to (3, 5, 1)
rez5 = rez4.reshape(3, 5, 1)
rez5

array([[[25.],
        [36.],
        [ 1.],
        [ 1.],
        [ 4.]],

       [[ 0.],
        [36.],
        [ 4.],
        [ 0.],
        [16.]],

       [[16.],
        [64.],
        [ 4.],
        [16.],
        [ 0.]]])

In [47]:
# Transpose the latest array
rez6 = rez5.T
rez6

array([[[25.,  0., 16.],
        [36., 36., 64.],
        [ 1.,  4.,  4.],
        [ 1.,  0., 16.],
        [ 4., 16.,  0.]]])

What does the transpose do?

In [49]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ra7 = np.random.randint(0, 10, size=(3, 3))
ra8 = np.random.randint(0, 10, size=(3, 2))
ra7, ra8

(array([[0, 8, 6],
        [8, 7, 0],
        [7, 7, 2]], dtype=int32),
 array([[0, 7],
        [2, 2],
        [0, 4]], dtype=int32))

In [50]:
# Perform a dot product on the two newest arrays you created
ra7.dot(ra8)

array([[16, 40],
       [14, 70],
       [14, 71]], dtype=int32)

In [51]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ra9 = np.random.randint(0, 10, size=(4, 3))
ra10 = np.random.randint(0, 10, size=(4, 3))
ra9, ra10

(array([[9, 6, 9],
        [8, 6, 8],
        [7, 1, 0],
        [6, 6, 7]], dtype=int32),
 array([[4, 2, 7],
        [5, 2, 0],
        [2, 4, 2],
        [0, 4, 9]], dtype=int32))

In [52]:
# Perform a dot product on the two newest arrays you created
ra9.dot(ra10)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [53]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
ra9.T.dot(ra10)

array([[ 90,  86, 131],
       [ 56,  52,  98],
       [ 76,  62, 126]], dtype=int32)

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [54]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
cr1 = np.random.randint(0, 10, size=(5, 6))
cr2 = np.random.randint(0, 10, size=(5, 6))

In [55]:
# Compare the two arrays with '>'
cr1 > cr2

array([[False,  True, False,  True,  True, False],
       [False, False, False,  True,  True, False],
       [False, False, False, False,  True,  True],
       [ True, False,  True, False,  True,  True],
       [ True,  True,  True, False, False,  True]])

What happens when you compare the arrays with `>`?

In [56]:
# Compare the two arrays with '>='
cr1 >= cr2

array([[False,  True,  True,  True,  True, False],
       [False, False, False,  True,  True, False],
       [False, False, False, False,  True,  True],
       [ True, False,  True, False,  True,  True],
       [ True,  True,  True, False,  True,  True]])

In [58]:
# Find which elements of the first array are greater than 7
cr1, cr1 > 7

(array([[6, 6, 8, 9, 9, 2],
        [6, 0, 3, 3, 4, 6],
        [6, 3, 6, 2, 5, 1],
        [9, 8, 4, 5, 3, 9],
        [6, 8, 6, 0, 0, 8]], dtype=int32),
 array([[False, False,  True,  True,  True, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [ True,  True, False, False, False,  True],
        [False,  True, False, False, False,  True]]))

In [59]:
# Which parts of each array are equal? (try using '==')
cr1 == cr2

array([[False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False]])

In [63]:
# Sort one of the arrays you just created in ascending order
np.sort(cr1)

array([[2, 6, 6, 8, 9, 9],
       [0, 3, 3, 4, 6, 6],
       [1, 2, 3, 5, 6, 6],
       [3, 4, 5, 8, 9, 9],
       [0, 0, 6, 6, 8, 8]], dtype=int32)

In [64]:
# Sort the indexes of one of the arrays you just created
np.argsort(cr1)

array([[5, 0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0, 5],
       [5, 3, 1, 4, 2, 0],
       [4, 2, 3, 1, 0, 5],
       [3, 4, 2, 0, 1, 5]])

In [66]:
# Find the index with the maximum value in one of the arrays you've created
cr1, np.argmax(cr1)

(array([[6, 6, 8, 9, 9, 2],
        [6, 0, 3, 3, 4, 6],
        [6, 3, 6, 2, 5, 1],
        [9, 8, 4, 5, 3, 9],
        [6, 8, 6, 0, 0, 8]], dtype=int32),
 np.int64(3))

In [67]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(cr1)

np.int64(7)

In [68]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(cr1, axis=1)

array([3, 0, 0, 0, 1])

In [69]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(cr1, axis = 0)

array([0, 1, 1, 4, 4, 2])

In [70]:
# Create an array of normally distributed random numbers
np.random.randn(3, 7)

array([[-0.06437805,  0.34490234, -0.08008734, -0.24138013,  1.43351549,
         1.06579371, -2.49875914],
       [ 1.48032856,  2.15872852,  1.23177838, -0.21432448, -0.68919421,
         0.72783311, -0.61906936],
       [ 0.35615983, -0.02188087,  1.21805044, -0.38945802, -0.44280234,
         0.37822661,  1.9338398 ]])

In [71]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.